### ISSUE TITLE
прочистить ужасы старого теха

### ISSUE THREAD

**Issue by bdemeshev** [bdemeshev/probability_hse_exams#1]
1. $$...$$ заменить на \\[...\\]. Готово (во всех файлах)! 
1. ... заменить на \ldots. Готово (во всех файлах)! 
1. сделать \item вместо ручных а) б) в)
1. перейти к сокращениям \P, \E, \Var, \Cov, \Corr, где оставлено старое
1. оформить таблицы по booktabs стандарту
1. у функций добавить \\, то есть должно быть \exp, \cos, etc
1. для нормального распределения \cN

начинать от прошлого года (как более актуального и полного) и идти к более древним

**Comment by olyagnilova** [comment]
Готово :)

**Comment by bdemeshev** [comment]
Отлично! :)
