### ISSUE TITLE
kr 1 base, 2016-2017, better solution

### ISSUE THREAD

**Issue by bdemeshev** [bdemeshev/probability_hse_exams#10]
Это задача из прошлой контрольной БП про двух людей, каждый из которых ставит один из 5 ответов наугад. Нужно сказать, с какой вероятностью все 17 у них совпадут. 
Рассмотрим первый вопрос. Х может выбрать первый вариант с вероятностью 1/5, Y может выбрать первый вариант с вероятностью 1/5. Тогда они оба могут одновременно выбрать этот вариант ответа с вероятностью 1/25. Однако таких вариантов в каждом вопросе 5, поэтому вся вероятность совпадения ответа в одном вопросе равна 1/5. Тогда все вопросы будут совпадать с вероятностью (1/5)^17.

by: Настя Жаркова

**Comment by olyagnilova** [comment]
Поменяла :)
