### ISSUE TITLE
КР1 2016-2017: опечатка

### ISSUE THREAD

**Issue by NastyaLapshina** [bdemeshev/probability_hse_exams#14]
КР1 БП 2016-2017: опечатка в решении 5 задачи b) когда случайная величина равна 100000. При подстановке значений  в условную вероятной при этта=2 ошибочно написано 0,9 (этого не должно быть, сам ответ 0,00(6) - правильный)

**Comment by olyagnilova** [comment]
Поправила! Большое спасибо :)
