### ISSUE TITLE
раздел с советами пишущим

### ISSUE THREAD

**Issue by bdemeshev** [bdemeshev/probability_hse_exams#15]
Добавить в документ минираздел для пишущих его :) 
Можно спереди малой главой размером на страничку :)

1. Никаких $$...$$, а только \\[...\\]. 
1. Никаких ... заменить на \ldots. 
1. Только \item вместо ручных а) б) в)
1. Сокращения \P, \E, \Var, \Cov, \Corr,
1. оформить таблицы по booktabs стандарту
1. у функций добавить \\, то есть должно быть \exp, \cos, etc
1. для нормального распределения \cN

Важно не дублировать учебники по теху, а изложить стилевые особенности коллекции.

**Comment by olyagnilova** [comment]
Добавила! Надеюсь, ничего не забыла :)
