### ISSUE TITLE
Опечатка в подборке экзаменов по теории вероятности

### ISSUE THREAD

**Issue by 1BSN** [bdemeshev/probability_hse_exams#18]
Здравствуйте, Борис Борисович, нашёл опечатку в 2017-2018 задача 8, неправильно посчитана выборочная дисперсия, а также деление этой дисперсии на (n-1), а не на n в выражении для доверительного интервала.

С уважением, 
Бадма

**Comment by olyagnilova** [comment]
Привет!
Про доверительный интервал согласна, сейчас поправлю
Ошибку в подсчете не вижу, там так посчитано: (190^2 + (-30)^2 + (-130)^2 + (-30)^2) / 3
Напиши, пожалуйста, как считаешь ты, так проще будет разобраться:)

**Comment by 1BSN** [comment]
Эх, устный счёт несколько подвёл...
