### ISSUE TITLE
two misprints

### ISSUE THREAD

**Issue by bdemeshev** [bdemeshev/probability_hse_exams#18]
нашла опечатки в подборке задач по теории вероятности:
1) с.208 задача 6д, там должен быть q 0,25, а в начале написано q 0,025
2) с.208 - пункты "и" и "к" перепутаны местами, решение которое написано в пункте "и" на самом деле отвечает на вопрос пункта "к"

by: Анна Демушкина

**Comment by olyagnilova** [comment]
исправила!
