### ISSUE TITLE
КР ИП 2014-2015 2 часть задачка №3

### ISSUE THREAD

**Issue by NikolayGolikov** [bdemeshev/probability_hse_exams#20]
КР ИП 2014-2015 2 часть задачка №3
 
Во-первых, в решении описка(наверное) "а из другого 2n-k спичек " (на самом деле n-k спичек).
Во-вторых, как мне кажется, в решение есть критическая ошибка, когда не учитывают, что последним ходом нужно взять именно из коробки, где нет спичек. В решении же просто считается вероятность, что не важно в каком порядке один коробок выбрали n+1 раз, а другой n-k раз.
![2017-10-23_22-51-22](https://user-images.githubusercontent.com/33165563/32126009-460edd7a-bb77-11e7-94dd-a8e7beb905d5.png)
![vcv4d19shhw](https://user-images.githubusercontent.com/33165563/32126010-4633bb7c-bb77-11e7-964d-620d4473a942.jpg)

**Comment by olyagnilova** [comment]
Готово!
Пункт (б) сначала не заметила, поэтому пока там старая вероятность, но я уже поправила, и после следующего коммита ошибки не будет.
Большое спасибо :)
