### ISSUE TITLE
Ошибка в ответах

### ISSUE THREAD

**Issue by ArefyevaDaria** [bdemeshev/probability_hse_exams#20]
В ответах варианта 2015-2016, номер 3, (стр. 208) дана формула совместной функции плотности норм распределения, в которой допущена ошибка, а именно неверно вынесены за скобку дисперсии x и y, если внести их, то получится ((x - m(x))^2)/ Var(y), аналогично с y

**Comment by bdemeshev** [comment]
Ага! Спасибо, поправили!
