### ISSUE TITLE
Опечатка в ответах КР-4 2016-2017

### ISSUE THREAD

**Issue by IsaevaNarmin** [bdemeshev/probability_hse_exams#24]
В ответах задачи 3 (пункта в) в качестве F(obs.) дано значение 0.5\0.6, что соответствует отношению данных в задаче выборочных стандартных отклонений. Разве не должно там быть отношение квадратов, то есть F(obs.)= 0.25\0.36?

**Comment by bdemeshev** [comment]
Ага! Спасибо, сейчас поправим! :)

**Comment by bdemeshev** [comment]
Исправлено!
