### ISSUE TITLE
Опечатка: кр 1 за 2016-2017 год, задача 6(г)

### ISSUE THREAD

**Issue by khaykingleb** [bdemeshev/probability_hse_exams#25]
В решении написано, что пассажир будет ждать **более** одной минуты, а не наоборот, как указано в условии, **менее** одной минуты. При этом ответ остается тем же.

То, что у меня выходит:
![IMG_3975](https://user-images.githubusercontent.com/42534632/66744869-37296980-ee86-11e9-9237-6b33c15310d5.jpg)

С уважением, 
Глеб Хайкин
БЭК1812

**Comment by bdemeshev** [comment]
не критичная, но для красоты поправил :) Спасибо!
