### ISSUE TITLE
Опечатка: кр 1 за 2018-2019 год, задача 1, задача 3

### ISSUE THREAD

**Issue by elizacc** [bdemeshev/probability_hse_exams#27]
В решении выписана вероятность, которую нужно посчитать, но во второй строке забыли прибавить вторую дробь. В третьей строке все уже хорошо

Еще в номере 3 пункт в) в первой строке функции распределения забыли поставить запятую :))

**Comment by bdemeshev** [comment]
Спасибо, сейчас закрою!
