### ISSUE TITLE
Задачный минимум к кр2. Номер 17-18

### ISSUE THREAD

**Issue by vio99** [bdemeshev/probability_hse_exams#27]
Должно быть:
17. 0,6422
18. 0,9544

**Comment by olyagnilova** [comment]
Здравствуйте!

Скорее всего дело в округлении. Сверьтесь, пожалуйста, с решениями ниже :) если ваше решение концептуально иное, делитесь :) 

Номер 17:
![photo_2017-12-04_13-58-45](https://user-images.githubusercontent.com/23439334/33549471-a94889da-d8fb-11e7-8ae2-272d8b6f4ec8.jpg)

Номер 18:
![photo_2017-12-04_13-58-39](https://user-images.githubusercontent.com/23439334/33549451-93264732-d8fb-11e7-87be-1d8c7bfd6812.jpg)

**Comment by bdemeshev** [comment]
```r
pnorm(26800, mean = 73 * 365, sd = sqrt(73 * 365)) - pnorm(26500, mean = 73 * 365, sd = sqrt(73 * 365))
pnorm(29250, mean = 100*289, sd = sqrt(100 * 289)) - pnorm(28550, mean = 100 * 289, sd = sqrt(100 * 289))
```
0.6416434
0.9604889

**Comment by olyagnilova** [comment]
Проверила ещё раз: пользуясь только таблицами и не сбрасывая числа с калькулятора, можно получить 0.6422 в 17 и 0.9606 в 18. Заменю на эти :)

**Comment by bdemeshev** [comment]
Лучше написать $\approx 0.64$ и $\approx 0.96$ :) Чтобы в дальнейшем исключить вопросы :)

**Comment by olyagnilova** [comment]
Да, добавила \approx в номера с 15 по 18)
