### ISSUE TITLE
Опечатка: кр 1 за 2018-2019 год, задача 3, задача 5

### ISSUE THREAD

**Issue by elizacc** [bdemeshev/probability_hse_exams#29]
Задача 3: не доделано решение к пункту д) -- не досчитана условная вероятность

Задача 5: в пункте б) вместо (5/11)^11 должно быть (6/11)^11, так как вероятность того, что кто-то не выберет со 2 по 6 этаж равна вероятности что он выберет с 7 по 12 этаж: 6/11

**Comment by bdemeshev** [comment]
ага, спасибо!
