### ISSUE TITLE
Неправильный ответ

### ISSUE THREAD

**Issue by alex1020304013** [bdemeshev/probability_hse_exams#29]
Возможно у вас ошибка в ответе на первую задачу пункт ж. Из задачного минимума.

Как известно, F(x) = P(X<x), а у вас ответ такой, что F(x) = P(X<=x). Это в свою очередь нарушает одно из свойств функции распределения: непрерывность слева.
Также и во многих задачах решение такое, будто F(x) = P(X<=x).

**Comment by bdemeshev** [comment]
Есть разные источники. В некоторых источниках функция плотности определяется как $F(x) = P(X < x)$, а в некоторых, как $F(x) = P(X \leq x)$.

Определение со строгим неравенством вводится, например, в замечательных [заметках Черновой](http://www.nsu.ru/mmf/tvims/chernova/tv/lec/node28.html). 

Однако определение $F(x) = P(X \leq x)$ является более популярным, например, [wolfram](http://mathworld.wolfram.com/DistributionFunction.html) или та же [википедия](https://ru.wikipedia.org/wiki/Функция_распределения). Именно его мы и придерживаемся.
