### ISSUE TITLE
вероятно ошибка в экзамен, 15.06.2015, вопрос 25

### ISSUE THREAD

**Issue by bdemeshev** [bdemeshev/probability_hse_exams#3]
![q15_15_06_2015](https://user-images.githubusercontent.com/1075773/30524148-d6d1cd90-9bf6-11e7-879d-8d9c0a2399a3.jpeg)

**Comment by olyagnilova** [comment]
В лекциях сумма рангов считалась по выборке, где наблюдений меньше, тогда получается 24, как и в ответах

**Comment by bdemeshev** [comment]
Оля, я не понял про лекции. Вроде в номере 25 в тесте 15.06.2015 дана именно эта выборка. И там в тесте неправильный ответ, или я что-то проглядел?

**Comment by olyagnilova** [comment]
Я имела в виду, что когда мы на лекции решали подобные задачи, мы пользовались вторым способом, но считали ранги по выборке, в которой наблюдений меньше. То есть мы складывали по зелёным: 4+5+6+9=24

**Comment by bdemeshev** [comment]
А, точно! Там два возможных значения, одно из которых 21, а другое — 24. Уточнил в условии :)
