### ISSUE TITLE
Опечатка: кр 1 за 2014-2015 год, задача 5, пункт б

### ISSUE THREAD

**Issue by khaykingleb** [bdemeshev/probability_hse_exams#31]
Мне кажется, дабы повысить прогностическую силу теста, необходимо увеличить чувствительность теста,— это P(A|B) в ответах, у меня P(З|Б).

Так, по крайней мере, выходит, если использовать формулу Байеса. Приложил решение.
![IMG_4086](https://user-images.githubusercontent.com/42534632/67151927-42d9bd80-f2d6-11e9-99ab-1584237ba990.jpg)

**Comment by bdemeshev** [comment]
В ответах всё ок. Проблема с низким P(B|A) вызвана тем, что очень много здоровых людей и тест существенное количество этих людей ошибочно считает якобы больными. Это значит, что повышать надо специфичность. Ты можешь расписать в общем виде и взять производные. Только надо помнить, что чувствительность входит и в числитель, и в знаменатель, а специфичность — входит в знаменатель.
