### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Werwo** [bdemeshev/probability_hse_exams#33]
Страница 230, номер 4, пункт б.
Случайная величина может быть равна 1 или 0, но потом при вычислении мат. ожидания взвешиваются -1 и 1. 
E(Xi) =-1*(1/2) + 1*(1/2) = 0
По всей видимости, нужно 0 на -1 поменять.

**Comment by olyagnilova** [comment]
Там опечатка была в определении случайной величины X_i: должно быть -1 и 1, так как имеется в виду шаг относительно начала координат.
Спасибо вам за внимательность! :)
