### ISSUE TITLE
очепятка

### ISSUE THREAD

**Issue by Symptotic** [bdemeshev/probability_hse_exams#34]
кр 2 б.п. 09.12.16 стр 229
задача 3 пункт б.
Исправить  
 1 - \frac{250}{100\cdot n} \leq  \mathbb{P} ( | \overline{\xi}_n - 250| >10 )
на                 
1 - \frac{250}{100\cdot n} \leq  \mathbb{P} ( | \overline{\xi}_n - 250| \leq 10 )

**Comment by olyagnilova** [comment]
спасибо!

**Comment by Symptotic** [comment]
Возможно стоит переделать  следующую фразу 
Найдём наименьшее целое n, при котором 0.99 \leq 1 - \frac{250}{100\cdot n} 

Найдём наименьшее целое n, при котором  левая часть неравенства ограничена снизу  0.99 \leq 1 - \frac{250}{100\cdot n}
