### ISSUE TITLE
Неправильный ответ

### ISSUE THREAD

**Issue by Werwo** [bdemeshev/probability_hse_exams#36]
Страница 238, вопрос 21. 
Матожидание числа выпавших шестерок: 5*{(1/6)*1+(5/6)*0}=5/6
Дисперсия числа выпавших шестерок: 5*{1/6*(1^2)+5/6*(0^2)} - (5/6)^2=30/36-25/36=5/36
То есть, ответ C.

P.S. Извиняюсь за кривое редактирование :(

**Comment by olyagnilova** [comment]
Здравствуйте!

Действительно, считая дисперсию, нужно использовать факт о том, что дисперсия суммы независимых случайных величин, равна сумме дисперсий.

Дисперсия при одном броске: (1/6 * (1^2) + 5/6 * (0^2)) - (1/6)^2 = 5/36
Дисперсия при пяти бросках: 5 * 5 /36 = 25/36

Получается, что верного ответа нет.
