### ISSUE TITLE
Определение из билетов к экзамену по теории вероятностей.

### ISSUE THREAD

**Issue by nickkiss** [bdemeshev/probability_hse_exams#37]
Что означает формулировка "Распределение функции от случайной величины"?

**Comment by bdemeshev** [comment]
Если случайные величины $X$ и $Y$ связаны соотношением $Y=h(X)$, то, зная закон распределения величины $X$, можно найти закон распределения величины $Y$.

Для величин с функцией плотности есть два способа. Один с производной обсуждался на лекции, второй — через дифференциальную форму обсуждался на семинаре. В этом вопросе требуется ответить, как связана функция плотности $X$ и функция плотности $Y$, если известна связь $h$ между $X$ и $Y$.
