### ISSUE TITLE
Возможная ошибка

### ISSUE THREAD

**Issue by alex1020304013** [bdemeshev/probability_hse_exams#38]
Возможная ошибка в решении задачи №2 из Контрольной работы 22.12.04
![shrek](https://user-images.githubusercontent.com/34339915/34180702-bb283908-e520-11e7-9ca6-b0ba1bd9317a.png)

Разве модуль не увеличивает вероятность в два раза?
Ведь при стандартизации числитель не всегда положителен, а здесь даже при отрицательном числителе есть удовлетворение условию. Я хочу сказать, что там не P(N(0,1)>2), а 2*P(N(0,1)>2). Видимо это опечатка, так как правильный ответ 0,0456 не сильно отличается.
При этом P(N(0,1)>2) = 1 -0.9772 = 0.0228

**Comment by olyagnilova** [comment]
Да, там действительно был пропущен множитель. Спасибо :)

**Comment by alex1020304013** [comment]
В описании файла написано, что за нахождение ошибок есть бонусы.
У меня будет бонус?
И если да, то какого плана?
ср, 20 дек. 2017 г. в 1:04, Olya Gnilova <notifications@github.com>:

**Comment by bdemeshev** [comment]
Не спрашивай, что бонусы могут сделать для тебя, спрашивай, что ты можешь сделать для бонусов :)

**Comment by alex1020304013** [comment]
Но ведь для бонуса я уже сделал)
ср, 20 дек. 2017 г. в 1:21, Boris Demeshev <notifications@github.com>:

**Comment by alex1020304013** [comment]
Плюс одна решенная задачка в тесте не помешает)
ср, 20 дек. 2017 г. в 1:29, Алекс Акопян <gimuser1993@gmail.com>:
