### ISSUE TITLE
Вопрос 20

### ISSUE THREAD

**Issue by trofimovdm** [bdemeshev/probability_hse_exams#39]
Борис Борисович, добрый день. Есть вопрос касаемо одного из номеров из вариантов прошлых лет. С одногруппницей получился ответ 7.3, в ключах ответ - 6.3. Не можем понять, где совершена ошибка. Прикрепляю вычисления и условия.
	С уважением,
	Трофимов Дмитрий(Бэк 161)
![vpxcfif1s3a](https://user-images.githubusercontent.com/34710279/34203578-c3d1a05a-e58c-11e7-9044-01deb45c29f1.jpg)
![6p2oc8y_jgm](https://user-images.githubusercontent.com/34710279/34203580-c816706e-e58c-11e7-8ecc-f50e2ba710a3.jpg)
![1pn3bw_sqeg](https://user-images.githubusercontent.com/34710279/34203581-ca4da596-e58c-11e7-9ca9-871e8cac2f49.jpg)

**Comment by olyagnilova** [comment]
Я не нахожу ошибки в решении. Видимо, ошибка в ответах
