### ISSUE TITLE
Экзамен 1 семестр 2017-12-21

### ISSUE THREAD

**Issue by RenataZam** [bdemeshev/probability_hse_exams#40]
Добрый день! 
Изучая вариант экзамена с ответами, я обратила внимание на следующие задания(см.решения+мои «идеи» решений). И я, к сожалению, не очень понимаю, почему в задачах получились именно эти ответы. Очень надеюсь, что Вы разъясните ответы и укажите, где я допустила ошибку. 
С уважением, 
Замалдинова Рената БЭК-165
EX=2; DX=6
P(X^2>100)=P(X>10)
По неравенству Маркова: P(X>10)<E|X|/x=2/10=1/5

СВ имеет равномерное распределение на [0;4]
P{3<кси<6}=F(6)-F(3)=(6-0/4)-(3-0/4)=3/4

**Comment by bdemeshev** [comment]
Неравенство Маркова применимо только к неотрицательным случайным величинам. А про $X$ такой информации нет. Поэтому здесь неравенство Маркова можно применять только к $X^2$.

Про $F(6)-F(3)$ верно, но поскольку величина $\xi$ равномерна на $[0;4]$ оказывается, что $F(6)=1$ и $F(3)=3/4$.
