### ISSUE TITLE
экзамен 2017, вопрос 28 

### ISSUE THREAD

**Issue by olyagnilova** [bdemeshev/probability_hse_exams#41]
Уточнить условие в задаче про тест знаков

**Comment by bdemeshev** [comment]
Похоже все ок. P-значение это вероятность наблюдать такую же или более экстремальную статистику. Есть два способа подсчёта, один плюсом считает одно, второй наоборот. Но экстремальность в первом случае это P(S>=2), а во втором P(Q<=1). И при верной H0 они равны :) Ведь Ho в симметрии закона!

**Comment by bdemeshev** [comment]
изменил там шкалу на 100-бальную, чтобы не тянуло никого считать вероятность совпадения баллов, и поставил альфу равную 0.51, чтобы избежать точного совпадения альфы с P-значением :)
