### ISSUE TITLE
КР4, 2017,  номер 1, пункт г

### ISSUE THREAD

**Issue by Pyatachokk** [bdemeshev/probability_hse_exams#46]
В статистике написаны дисперсии, но подставлены стандартные отклонения. Статистика посчитана неверно.

Ещё в номере 4 при подсчёте статистики лучше указывать в дисперсии не выборочную долю, а долю из гипотезы H0 из-за ассимптотики, но чёрт знает, по идее это не такая и ошибка

**Comment by olyagnilova** [comment]
Спасибо!
В первом номере немного хитрее: там в условии стандартное отклонение, а в гипотезе – дисперсия :)
Четвёртое менять не стала, чтобы было, как на лекции
