### ISSUE TITLE
Опечатка: кр 2 за 2009-2010 год, задача 3

### ISSUE THREAD

**Issue by khaykingleb** [bdemeshev/probability_hse_exams#47]
В решении написано, что в пункте (в) ответ 0.75

А у меня выходит, что 0.25

![IMG_2908](https://user-images.githubusercontent.com/42534632/70051844-f37bf200-15e2-11ea-95bb-c51ac0b7fc3a.JPG)

**Comment by bdemeshev** [comment]
Спасибо, поправили!
