### ISSUE TITLE
Экзамен 2016

### ISSUE THREAD

**Issue by Pyatachokk** [bdemeshev/probability_hse_exams#48]
Вопрос 12, в задании перепутаны местами мат. ожидание и среднее

**Comment by olyagnilova** [comment]
да, но это не означает, что такой статистикой нельзя проверить гипотезу о матожидании :)

**Comment by bdemeshev** [comment]
более того, именно в этом и была идея автора вопроса :)

**Comment by Pyatachokk** [comment]
Догадываюсь, кто был автором

**Comment by bdemeshev** [comment]
Не угадал. Дима.
