### ISSUE TITLE
Опечатка: кр-2 2007-2008 Демо-версия, задача 6

### ISSUE THREAD

**Issue by khaykingleb** [bdemeshev/probability_hse_exams#49]
В решении написано, что
<img width="1163" alt="Screen Shot 2019-12-04 at 7 31 38 PM" src="https://user-images.githubusercontent.com/42534632/70161261-d58abc00-16cc-11ea-8bd8-7b0f2153095a.png">

А у меня выходит, что
![IMG_5731](https://user-images.githubusercontent.com/42534632/70161375-066af100-16cd-11ea-9f29-275e15cf512b.JPG)
![IMG_4094](https://user-images.githubusercontent.com/42534632/70161389-0d91ff00-16cd-11ea-9f8c-18e5c5f19477.JPG)

**Comment by khaykingleb** [comment]
В 7 задаче опечатка в вычислениях: n = 15851

**Comment by bdemeshev** [comment]
Мерси, исправили!
