### ISSUE TITLE
Экзамен 2016-2017

### ISSUE THREAD

**Issue by Werwo** [bdemeshev/probability_hse_exams#51]
Вопрос 22: Почему не подходит C?
Вопрос 28: У меня выходит уровень значимости под 0,7. По идее, при уровне значимости 0,51 p с крышкой должно быть очень близко к 0,5, но это не так. Не понимаю(

И здесь же добавлю вопрос по номеру 17 из экзамена 2015-2016 - тоже не понимаю, почему 1/2.

**Comment by olyagnilova** [comment]
Вопрос 22: нужно вспомнить, какие предпосылки используются при тестировании гипотезы о математическом ожидании при неизвестной дисперсии — на малых выборках предполагаем нормальность распределения иксов. Подробности – в разделе «Шпаргалка» в самом конце [листочков по вероятностям](https://github.com/bdemeshev/probability_pro/raw/master/probability_pro.pdf) :)

Вопрос 28: возможно, помогут эти [пояснения](https://github.com/bdemeshev/probability_hse_exams/issues/41), если нет, то уточните вопрос :)

Вопрос 17: ответ такой же как и на предыдущий вопрос
