### ISSUE TITLE
Задача 17, экзамен 2016 года

### ISSUE THREAD

**Issue by ashestyaeva** [bdemeshev/probability_hse_exams#52]
Поскажите, пожалуйста, как понять, какая альтернативная гипотеза в этом случае? Как я понимаю, в ответе имелось в виду, что один из вариантов должен быть лучше, то есть имелась в виду односторонняя гипотеза?  Спасибо.

**Comment by bdemeshev** [comment]
Да. Сейчас добавлю уточненние! Спасибо :)
