### ISSUE TITLE
Опечатка: кр 2 за 2013–14 год, задача 2

### ISSUE THREAD

**Issue by khaykingleb** [bdemeshev/probability_hse_exams#55]
В решении написано, что
<img width="1183" alt="Screen Shot 2020-01-23 at 2 09 26 PM" src="https://user-images.githubusercontent.com/42534632/72979734-0abcac00-3dea-11ea-99ea-b1d4242c51ff.png">
<img width="1183" alt="Screen Shot 2020-01-23 at 2 09 32 PM" src="https://user-images.githubusercontent.com/42534632/72979739-0c866f80-3dea-11ea-82e1-6a764d402447.png">

А у меня выходит, что
![XQP4C4V3Hq4](https://user-images.githubusercontent.com/42534632/72990827-ecfb4100-3e01-11ea-9e0f-b6872246ede4.jpg)
![T9ErAevq1uw](https://user-images.githubusercontent.com/42534632/72979832-39d31d80-3dea-11ea-94a1-04b18bf66912.jpg)

**Comment by Sekretarin** [comment]
С твоим пунктов в) согласен частично (не понял твою стандартизацию), с пунктом д) согласен полностью. Спасибо за бдительность!

Вот код обновленного решения:

```
В пункте в) произошла ошибка. Действительно, чтобы искать вероятность, найдем параметры новой случ. величины (мат. ожидание и дисперсию):

\[\E(Y|X=x) = \mu_{y} + \Corr(X, Y)\cdot \sigma_{y}\cdot \frac{x-\mu_{x}}{\sigma_{x}}\]
\[\Var(Y|X=x) = \sigma^{2}_{y}\cdot (1 - \Corr^{2}(X, Y))\]

Посчитаем...

\[\E(Y|X=x) = 0 - \frac{1}{6}\cdot 2 \cdot \frac{1-0}{3} = -\frac{1}{9}\]
\[\Var(Y|X=x) =4\cdot (1 - \frac{1}{36}) = \frac{35}{9} \]

А теперь нужно стандартизировать:

\[\P(2X + Y >3|X=1) = \P(Y>1|X=1) = \P(\frac{Y - \E}{\sqrt{\Var}}>\frac{1 - \E}{\sqrt{\Var}})\]

\[\P(Y>1|X=1) = \P(N(0,1)>  \approx 0.56) = 1-\phi(0.56) = 1 - 0.56 = 0.44\]

В пункте д) также была допущена ошибка. Действительно, по формуле:

\[f(x,y) = \frac{1}{2\pi}\cdot\frac{1}{\sigma^{2}_{x}\cdot\sigma^{2}_{y}(1-\Corr^{2})}\cdot \exp^{-0.5(x-\mu_{x}, y - \mu_{y})\cdot C^{-1}\cdot (x-\mu_{x}, y - \mu_{y})^{T}}, \]

где $C^{-1}$ есть обратная к ковариационной матрица

Подставляем и получаем:

\[f(x,y) = \frac{1}{2\pi}\cdot \frac{1}{\sqrt{35}}\cdot \exp^{-0.5\cdot (X,Y)\cdot C^{-1} \cdot (X,Y)^{T}}, \]

где $C^{-1}$ есть:

\begin{pmatrix}
  \frac{4}{35} & \frac{1}{35}\\
  \frac{1}{35} & \frac{9}{35}
\end{pmatrix}

В итоге получаем:

\[f(x,y) = \frac{1}{2\pi}\cdot \frac{1}{\sqrt{35}}\cdot \exp^{\frac{1}{70}\cdot(4x^{2}+2xy+9y^{2})}\]
```

**Comment by khaykingleb** [comment]
Да, со стандартизацией я ошибся: про знак забыл. Но там не 2/7, а `$\dfrac{\frac{10}{9}}{sqrt(\frac{35}{9})} \approx 0.56$`

**Comment by Sekretarin** [comment]
Согласен, спасибо)
Изменил первый коммент, чтобы с него брать код

**Comment by bdemeshev** [comment]
По теху на будущее:
- `\[` и `\]` лучше на отдельной строке писать
-  писать просто `\E` без аргумента не модно :) либо число, либо полностью от чего `\E`
- `\begin{pmatrix}` требует нового уравнения `\[`
- в сборнике определено сокращение для нормального `\cN`

но это мне уже быстрее самому на месте поправить :) спасибо за решение :)
