### ISSUE TITLE
Опечатка: задачный минимум, кр 1, страница 6, одна большая очепятка

### ISSUE THREAD

**Issue by donpoissonnabaze** [bdemeshev/probability_hse_exams#56]
В решении написано, что первый номер: а)0.6, в)зависимы
второй номер: появляются неожиданные пункты а, б и в, которых нет, а ответ на задачу под номером 2 почему-то в ответе на задачу 3! Где искать ответы на решения задач 3 и 4 оказалось абсолютно неясным, потому что в них содержатся подпункты "а, б" - в решениях же какие-то единичные ответы.

А у меня выходит, что первый номер: а)0.7, в)независимы

Мы с моим другом зеленым драконом Доном Пуассоном так расстроились, что даже не пошли дальше, а подготовка к пересдаче наступает нам на пятки!

**Comment by bdemeshev** [comment]
Спасибо за внимательность! Мы в курсе этой проблемы — ответы висят к старой
версии минимума. Пока что можно готовиться по условиям без ответов, они
корректные. При вопросах по решению можно ловить семинаристов или
ассистентов. Постараемся устранить побыстрее :)

Il mar 28 gen 2020, 05:21 donpoissonnabaze <notifications@github.com> ha
scritto:

**Comment by bdemeshev** [comment]
Закрыли! Спасибо летит к Лизе :)
