### ISSUE TITLE
Опечатка: кр 4 за 2014/2015 год, задача 1 а) для первого потока

### ISSUE THREAD

**Issue by EvgNikulina** [bdemeshev/probability_hse_exams#63]
В решении написано, что... вероятность увидеть Халявина на занятии лежит от -0.56 до 1.36 что само по себе невозможно

А у меня выходит, что... 95% ДИ вероятности (0.25  0.55)

**Comment by MrMO1337** [comment]
Полностью уверен, что опечатка есть.
Автор абсолютно прав, в решении допущена вычислительная ошибка в последней строчке.
Правильный ответ: 0,25 < p < 0,55
