### ISSUE TITLE
Опечатка: листки ИП, задача 27.10

### ISSUE THREAD

**Issue by semasolomonov** [bdemeshev/probability_hse_exams#64]
![photo_2020-05-24 12 16 56](https://user-images.githubusercontent.com/63566319/82750386-7cb4fa00-9db8-11ea-98a1-022802a4150e.jpeg)
В условии задачи отсутствует предпосылка о независимости случайных величин. Без этого предположения не получается составить функцию правдоподобия для построения РНМК.

Если же предпосылка о независимости есть, то задача становится похожей на решабельную, потому что тогда основная гипотеза эквивалентна тому, что `$f(x_1,x_2) = 1, x \in [0;1]$`(альтернативная тоже о совместной плотности).

**Comment by bdemeshev** [comment]
Спасибо :) закрыто в другом репозитории!
