### ISSUE TITLE
Ошибка в ответах: КР1, Задачаный минимум, задача 9, пункт г).

### ISSUE THREAD

**Issue by Ilyasl2000** [bdemeshev/probability_hse_exams#71]
В ответах написано, что правильный ответ к пункту г) (1 - (5/9)^5).

А у меня выходит, что правильный ответ C_из_5_по_0 * (5/9)^0 * (1 - 5/9)^5, потому что (1 - (5/9)^5) = C_из_5_по_0 * (5/9)^0 * (1 - 5/9)^5 + C_из_5_по_1 * (5/9)^1 * (1 - 5/9)^4 + ... + C_из_5_по_4 * (5/9)^4 * (1 - 5/9)^1.

**Comment by bdemeshev** [comment]
можно проще #70 
поправил!
