### ISSUE TITLE
Опечатка: кр 1 задачный минимум, задача 7

### ISSUE THREAD

**Issue by AlexandrMIKHAOLOV** [bdemeshev/probability_hse_exams#72]
В решении написано, что в пункте е этой задачи ответ 2,3

А у меня выходит, что , согласно формуле pn-q<k<np+q  k заключено между границами 2,75 и 3,25 (так как n=4, а p=0,75). Единственное значение, подходящее в интервал = 3. То есть ответ в задаче неверный

**Comment by bdemeshev** [comment]
Мерси! :)
