### ISSUE TITLE
Опечатка: Задачный минимум КР1, 9 задача, пункт г

### ISSUE THREAD

**Issue by AlexandrY99** [bdemeshev/probability_hse_exams#73]
В ответах написано 1-(5/9)^5, правильный ответ (4/9)^5

**Comment by bdemeshev** [comment]
Александр, да, была такая опечатка :) Только она была убита ещё 3 октября :) Скачивай свежую версию :)

**Comment by AlexandrY99** [comment]
Окей, пошел апдейтить :)

ср, 14 окт. 2020 г. в 12:23, Boris Demeshev <notifications@github.com>:
