### ISSUE TITLE
Опечатка: кр 1 Демо-версия 2008-2009 год, задача 6 пункт в

### ISSUE THREAD

**Issue by AlexandrMIKHAOLOV** [bdemeshev/probability_hse_exams#74]
В решении написано, что E(XY) = 0

А у меня выходит, что E(XY) = 0.1

Пусть Z = XY, тогда:
Z = -1,0,2
p(Z = -1) = 0.1
p(Z = 0) = 0.2 + c + 0.2 + 0.2 = 0.8
p(Z = 2) = 0.1
E(XY) = E(Z) = -0.1 + 0.2 = 0.1

**Comment by AlexandrMIKHAOLOV** [comment]
спасибо, ошибка

**Comment by bdemeshev** [comment]
Ага! Мерси!
