### ISSUE TITLE
Опечатка: кр №2 за 2019-2020 год задание №4

### ISSUE THREAD

**Issue by BobrovaOlga** [bdemeshev/probability_hse_exams#79]
В решении написано, что P(X<=20)=1-P(X>=20)

А у меня выходит, что P(X<=20)=1-P(X>20)  в силу дискретности случайной величины Х 
То есть P(X<=20)=1-P(X>=21)

**Comment by AlexandrMIKHAOLOV** [comment]
Да, это верно. В данной задаче не особо значим этот недочет, но мы все равно учтем данную ошибку и поправим.

**Comment by bdemeshev** [comment]
Ага, поправили! Спасибо!
