### ISSUE TITLE
Опечатка в ответе 29, 16.2 на странице 268 

### ISSUE THREAD

**Issue by vladimir112358** [bdemeshev/probability_hse_exams#85]
В ответах 16.2 на странице 268 написано ответом на 29 вопрос "B"
А мне думается, что правильно "A"

было:
AE?BA XBCEB BB?CA BBCCC ABCBA E⁇BC
кажется правильным:
AE?BA XBCEB BB?CA BBCCC ABCBA E⁇AC

**Comment by bdemeshev** [comment]
Ага, верно! Спасибо!
